version: 2
registries:
  # Vedlikehold avhengigheter for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

  # Vedlikehold avhengigheter for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
